# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@2.0.0

jobs:
  distribute:
    executor:
      name: android/android-machine
    steps:
      - flutter/install_sdk_and_pub:
          version: 3.0.3
      - flutter/install_android_gradle_dependencies
      - flutter/install_android_gem
      - run:
          command: bundle exec fastlane distribute
          working_directory: android
workflows:
  test:
    jobs:
      - flutter/lint:
          version: 3.0.3
      - flutter/unit_test:
          version: 3.0.3
  distribute:
    jobs:
      - distribute
